export const productsData = [
    {
        slug: 'ethiopia-yirgacheffe',
        name: 'Ethiopia Yirgacheffe',
        tagline: 'Jasmine, bergamot, and a finish like iced tea',
        category: 'Beans',
        priceCents: 1850,
        imageUrl: '/images/products/ethiopia-yirgacheffe.jpg',
        stock: 120,
        featured: true,
    },
    {
        slug: 'colombia-huila',
        name: 'Colombia Huila',
        tagline: 'Caramel, red apple, comfortably classic',
        category: 'Beans',
        priceCents: 1600,
        imageUrl: '/images/products/colombia-huila.jpg',
        stock: 200,
        featured: true,
    },
    {
        slug: 'hario-v60-02',
        name: 'Hario V60 Dripper 02',
        tagline: 'The cone that started a thousand arguments',
        category: 'Equipment',
        priceCents: 2400,
        imageUrl: '/images/products/hario-v60-02-3.jpg',
        stock: 45,
        featured: true,
    },
    {
        slug: 'comandante-c40',
        name: 'Comandante C40 Grinder',
        tagline: 'Hand grinder. Heirloom burrs. Cries in luxury.',
        category: 'Equipment',
        priceCents: 29500,
        imageUrl: '/images/products/comandante-c40-3.webp',
        stock: 12,
        featured: true,
    },
]