export const productsData = [
  {
    slug: 'ethiopia-yirgacheffe',
    name: 'Ethiopia Yirgacheffe',
    tagline: 'Jasmine, bergamot, and a finish like iced tea',
    description: 'Grown at 1,900m in the Gedeo zone and washed at the Idido station. This is the coffee people mean when they say coffee can taste like flowers. Bright, clean, and almost tea-like in the cup.',
    origin: 'Ethiopia',
    roast: 'Light',
    category: 'Beans',
    priceCents: 1850,
    imageUrl: '/images/products/ethiopia-yirgacheffe.jpg',
    stock: 120,
    featured: true,
  },
  {
    slug: 'colombia-huila',
    name: 'Colombia Huila',
    tagline: 'Caramel, red apple, comfortably classic',
    description:
      'The dependable one. Huila sits in the south of Colombia where altitude and steady rainfall produce a cup that is sweet without being sugary. Works in every brew method, forgives a sloppy grind.',
    origin: 'Colombia',
    roast: 'Medium',
    category: 'Beans',
    priceCents: 1600,
    imageUrl: '/images/products/colombia-huila.jpg',
    stock: 200,
    featured: true,
  },
  {
    slug: 'hario-v60-02',
    name: 'Hario V60 Dripper 02',
    tagline: 'The cone that started a thousand arguments',
    description:
      'Ceramic, 60-degree cone, one big hole at the bottom. That single large opening is the whole point: it puts brew time in your hands instead of the dripper\'s. Steeper learning curve, higher ceiling once you get there.',
    origin: null,
    roast: null,
    category: 'Equipment',
    priceCents: 2400,
    imageUrl: '/images/products/hario-v60-02-3.jpg',
    stock: 45,
    featured: true,
  },
  {
    slug: 'comandante-c40',
    name: 'Comandante C40 Grinder',
    tagline: 'Hand grinder. Heirloom burrs. Cries in luxury.',
    description:
      'Nitrogen-hardened steel burrs, a stepped adjustment you can actually remember, and a grind consistency that embarrasses electric grinders three times the price.',
    origin: null,
    roast: null,
    category: 'Equipment',
    priceCents: 29500,
    imageUrl: '/images/products/comandante-c40-3.webp',
    stock: 12,
    featured: true,
  },
]